### PR TITLE
Git client update: allow URL as location and use git library for git operations

### PR DESCRIPTION
**Pull request by jsuchome**
See

- https://github.com/fuseml/fuseml/issues/123
- https://github.com/fuseml/fuseml/issues/114

### CODE REVIEW

**Review by stefannica — APPROVED** [review]
Looks good

**Comment by jsuchome** [comment]
@stefannica do you know of better way for providing help text for positional argument than the one I've used?

**Review by flaviodsr — APPROVED** [review]
Very cool!

I wonder if it would make sense to consider forking the repository into Gitea instead of cloning and pushing.

**Comment by stefannica** [comment]
> Very cool!
> 
> I wonder if it would make sense to consider forking the repository into Gitea instead of cloning and pushing.

Good point, it didn't even occur to me that it was an option.

It's not that simple to do that with gitea though, first you need to create a mirror of the upstream repo, and only then you can fork it: https://www.reddit.com/r/Gitea/comments/fsxcel/fork_from_github/

**Comment by flaviodsr** [comment]
> > Very cool!
> > I wonder if it would make sense to consider forking the repository into Gitea instead of cloning and pushing.
> 
> Good point, it didn't even occur to me that it was an option.
> 
> It's not that simple to do that with gitea though, first you need to create a mirror of the upstream repo, and only then you can fork it: [reddit.com/r/Gitea/comments/fsxcel/fork_from_github](https://www.reddit.com/r/Gitea/comments/fsxcel/fork_from_github/)

I think that is the case only when you want to also get the changes submitted to the original repo. I manually tried it on Gitea web UI and it was easy to do. There is even an option for mirroring which the gitea go-sdk probably also offer.

**Comment by jsuchome** [comment]
Yeah, there are different ways of doing it.

If you notice the original code done by `git` client, it was also different - but I wasn't able to reproduce it using `go-git` (believe it or not, but I was not able to create local branch and switch into it).

So I'm happy I got at least one working solution.

**Comment by stefannica** [comment]
> @stefannica do you know of better way for providing help text for positional argument than the one I've used?


Support for positional arguments is still somewhat lacking with cobra. You can experiment with writing you own multi-line `.Use` value. You can disable the `[flags]` suffix automatically added by the cobra framework by setting this option:

```
	// DisableFlagsInUseLine will disable the addition of [flags] to the usage
	// line of a command when printing help or generating docs
	DisableFlagsInUseLine bool
```

You can also make it more clear by configuring an `.Example` (which we didn't yet do with any of the commands).

**Comment by jsuchome** [comment]
help on top (current PR):
```
Register a codeset with FuseML. Location can be path to directory or URL of git repository.

Usage:
  fuseml codeset register {-n|--name NAME} {-p|--project PROJECT} {-d|--desc DESCRIPTION} [--label LABEL] LOCATION
```

help as a part of multi-line .Use value:
```
Register a codeset with FuseML.

Usage:
  fuseml codeset register {-n|--name NAME} {-p|--project PROJECT} {-d|--desc DESCRIPTION} [--label LABEL] LOCATION

LOCATION can be path to local directory or URL of a git repository [flags]

Flags:
```

**Comment by jsuchome** [comment]
I took the second option, with multiline Use

**Review by flaviodsr — APPROVED** [review]

**Review by stefannica — APPROVED** [review]
Kill to birds with one stone, well done !

**Pull request merged**
